port: 9443
metricBindAddress: ":8080"
healthProbeBindAddress: ":8081"
enableLeaderElection: false
leaderElectionID: "85d48caf.fcp.ottoscalr.io"
metricsScraper:
  prometheusUrl: "http://localhost:9090"
  queryTimeoutSec: 30
  querySplitIntervalHr: 24
breachMonitor:
  pollingIntervalSec: 300
  cpuRedLine: 0.85
  stepSec: 30
periodicTrigger:
  pollingIntervalMin: 360
policyRecommendationController:
  maxConcurrentReconciles: 1
  policyExpiryAge: 48h
policyRecommendationRegistrar:
  requeueDelayMs: 500
cpuUtilizationBasedRecommender:
  metricWindowInDays: 28
  stepSec: 30
  minTarget: 10
  maxTarget: 60
metricIngestionTime: 15.0
metricProbeTime: 15.0
enableMetricsTransformer: false
eventCallIntegration:
  eventCalendarAPIEndpoint: "http://10.83.36.132/fk-event-calendar-service/v1/eventCalendar/search"
  eventFetchWindowInHours: "1"
nfrDataConfigMapName: "nfr-data-config"


